apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespaces.nexusNs }}
  name: {{ .Chart.Name }}-{{ .Chart.Version }}.{{ .Release.Name }}-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- if .Values.ingress.hosts }}
  - hosts:
  {{- range .Values.ingress.hosts }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $.Chart.Name }}-service
              port:
                number: {{ $.Values.service.nexus.port }}
    {{- end }}
    {{- else }}
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $.Chart.Name }}-service
              port:
                number: {{ $.Values.service.nexus.port }}
    {{- end }}

---
{{- if .Values.ingress.dockerIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespaces.nexusNs }}
  name: {{ .Chart.Name }}-{{ .Chart.Version }}.{{ .Release.Name }}-ingress-nxrm-docker
  {{- with .Values.ingress.dockerIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.dockerIngress.tls }}
  tls:
  {{- if .Values.ingress.dockerIngress.hosts }}
  - hosts:
  {{- range .Values.ingress.dockerIngress.hosts }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
    secretName: {{ .Values.ingress.dockerIngress.tls.secretName }}
  {{- end }}
  rules:
    {{- if .Values.ingress.dockerIngress.hosts }}
    {{- range .Values.ingress.dockerIngress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $.Chart.Name }}-docker-service
              port:
                number: {{ $.Values.service.docker.port }}
    {{- end }}
    {{- else }}
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $.Chart.Name }}-docker-service
              port:
                number: {{ $.Values.service.docker.port }}
    {{- end }}
{{- end}}
